name: plant_diagnosis
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tflite: ^1.1.1
  percent_indicator: ^2.1.1+1
  image_picker: ^0.7.2+1
  moor_flutter: ^4.0.0
  flutter_mobx: ^1.1.0+2
  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  flutter_polyline_points: ^0.2.6
  path_provider: ^2.0.1
  sqlite3_flutter_libs: ^0.2.0
  intl: ^0.17.0
  flutter_slidable: ^0.5.7
  material_design_icons_flutter: ^4.0.5955

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator:
  mobx_codegen: ^1.1.0
  build_runner: ^1.11.0

dependencies_overrides:
  # mobx_codegen: ^2.0.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - assets/strawberries/labels.txt
    - assets/strawberries/model_unquant.tflite

    - assets/images/image.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
